name: Scala CI

on:
- push
- pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        sbt-args:
        - ''
        - --addPluginSbtFile=project/plugins.sbt.scalajs06
        scala:
        - 2.11.12
        - 2.12.11
        - 2.13.4
        exclude:
          - scala: 2.11.12
            sbt-args: ''
          - scala: 2.12.11
            sbt-args: ''

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Need the git history for sbt-dynver to determine the version
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: | 
          ~/.ivy2/cache/
          ~/.sbt/
          ~/.coursier/
        key: |
          ${{runner.os}}-${{matrix.scala}}-${{hashFiles('**/*.sbt')}}-${{matrix.sbt-args}}
          ${{runner.os}}-${{matrix.scala}}-${{hashFiles('**/*.sbt')}}
          ${{runner.os}}-${{matrix.scala}}-
    - name: Run tests
      run: sbt ${{matrix.sbt-args}} ++${{matrix.scala}} test
    - name: Publish to Maven Central Repository
      env:
        SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}
        SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}
      if: ${{env.SONATYPE_USERNAME != ''}}
      run: |
        openssl aes-256-cbc -K ${{secrets.encrypted_69821ba7448c_key}} -iv ${{secrets.encrypted_69821ba7448c_iv}} -in secring.asc.enc -out secring.asc -d
        sbt ${{matrix.sbt-args}} ++${{matrix.scala}} "set every Seq(sonatypeSessionName := \"${{github.workflow}} ${{github.run_id}} ${{github.run_number}} ${{github.run_attempt}} ${{matrix.scala}}\", publishTo := sonatypePublishToBundle.value)" publishSigned sonatypeBundleRelease
